# Uncomment the next line to define a global platform for your project
 platform :ios, '10.3.2'

target 'map' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for map

  target 'mapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mapUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  source 'https://github.com/CocoaPods/Specs.git'
  pod 'GoogleMaps'
  pod 'GooglePlaces'


end
